### ISSUE TITLE
Workaround for d3plot files with temperature information

### ISSUE THREAD

**Issue by Lizardworkinghard** [qd-cae/qd-cae-python#14]
I try to read a series of d3plot files from an uncontrolled source (somebody else produced them) and found 
`RuntimeError: dyna_it != 0: Can not handle temperatures.`

**Comment by qd-codie** [comment]
had this topic just a few days ago for the first time. It seems that dyna writes mass scaling information into the temperature field and I didn't know about that. I will fix it when I find some spare time and add it to the next release. For the moment you have two options:

  1. Do not output mass scaling information
  2. Use [plotcompress](https://www.dynamore.de/de/produkte/tools/plotcprs) to discard temperatures

**Comment by qd-codie** [comment]
Ok finally I got some time for the fix. I will add it to the 0.7.0 build, which might make it this weekend.

**Comment by qd-codie** [comment]
The D3plot class can now read files with mass scaling info (still not with temperatures though).
