### ISSUE TITLE
qd.cae.dyna import fail

### ISSUE THREAD

**Issue by NKlinke** [qd-cae/qd-cae-python#18]
Hi codie,

i recently wanted to try the current version for a project. I installed it into my environment with pip

> python -m pip install qd
> Collecting qd
>   Downloading qd-0.7.1-cp35-cp35m-win_amd64.whl (1.7MB)
>     100% |################################| 1.7MB 656kB/s
> Requirement already satisfied (use --upgrade to upgrade): h5py in d:\trb_cae\python\miniconda3\envs\py35_d\lib\site-packages (from qd)
> Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8 in d:\trb_cae\python\miniconda3\envs\py35_d\lib\site-packages (from qd)
> Collecting diversipy (from qd)
>   Downloading diversipy-0.7.tar.gz
> Collecting pybind11>=2.2.0 (from qd)
>   Downloading pybind11-2.2.2-py2.py3-none-any.whl (144kB)
>     100% |################################| 153kB 3.3MB/s
> Requirement already satisfied (use --upgrade to upgrade): six in d:\trb_cae\python\miniconda3\envs\py35_d\lib\site-packages (from h5py->qd)
> Requirement already satisfied (use --upgrade to upgrade): scipy in d:\trb_cae\python\miniconda3\envs\py35_d\lib\site-packages (from diversipy->qd)
> Building wheels for collected packages: diversipy
>   Running setup.py bdist_wheel for diversipy ... done
>   Stored in directory: C:\Users\klinken\AppData\Local\pip\Cache\wheels\0a\d2\46\06009397470774284dfb20f6f8d8cbf93b96a2b9bece53567c
> Successfully built diversipy
> Installing collected packages: diversipy, pybind11, qd
> Successfully installed diversipy-0.7 pybind11-2.2.2 qd-0.7.1
> You are using pip version 8.1.2, however version 9.0.2 is available.
> You should consider upgrading via the 'python -m pip install --upgrade pip' command.

But when i try to import it get the following error: 

> Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.
> 1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
>  from qd.cae.dyna import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\TRB_CAE\Python\Miniconda3\envs\py35_d\lib\site-packages\qd\cae\dyna.py", line 4, in <module>
>     from .dyna_cpp import *
> SystemError: initialization of dyna_cpp raised unreported exception

Can you help me with this?

**Comment by qd-codie** [comment]
Hmm could be a dll issue, best call me, I think its easier :)

**Comment by qd-codie** [comment]
Hey Niklas,
I'm not sure whether I compiled the package with VS 2017 for the first time. In such a case the Redistributionals for VS17 might be missing (some dlls which are required to run modern c++ programs on windows). Maybe try downloading and installing them as shown below:

https://www.visualstudio.com/de/downloads/?rr=https%3A%2F%2Fsocial.msdn.microsoft.com%2F

![grafik](https://user-images.githubusercontent.com/5020407/37876674-756e31bc-3050-11e8-8f1a-7f6e130cb970.png)

Unfortunately you will have to be a guinea pig here :stuck_out_tongue:

**Comment by NKlinke** [comment]
Hi codie,

i checked and I already had this one installed. After updating it, the error remains the same 

Does the content of the folder look correct to you?

![grafik](https://user-images.githubusercontent.com/17301532/38025487-e6c76efc-3288-11e8-9a21-43c81c1d7417.png)

**Comment by qd-codie** [comment]
Did you have any success with the suggestions we talked about?

**Comment by NKlinke** [comment]
Hi codie,

after setting up a fresh 3.6 environment with anaconda, import works well. 
Thank you for your help!

**Comment by qd-codie** [comment]
Hey Niklas :rabbit: 
glad it worked :smile: Tell me if you encounter more issues.
