### ISSUE TITLE
Change logic for encryption detection without entropy calculation

### ISSUE THREAD

**Issue by hoo-ray** [qd-cae/qd-cae-python#24]
In LS-Dyna keyword files, encrypted data is embedded between two header/footer lines:
```
-----BEGIN PGP MESSAGE-----
Encrypted data
-----END PGP MESSAGE-----
```
The keyfile parser should search for these lines and then skip encrypted data on a per-line-basis.
**Advantages:**
- improvement in speed because entropy calculation is dropped
- support for mixed keyfiles containing both encrypted and unencrypted input data (e.g. unencrypted *MAT keywords with encrypted *DEFINE_TABLE, *DEFINE_CURVE yield curves)

**Comment by qd-codie** [comment]
Planned for 0.8

**Comment by qd-codie** [comment]
The library now checks for `"-----BEGIN PGP"`, searches the matching `"-----END PGP"` and extracts the data inbetween. All together is placed in an own keyword with currently still an empty name `''`.
