### ISSUE TITLE
can not get parts objects by ID if set a part id list

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#27]
keyWord=KeyFile(fileName)
        parts=keyWord.get_partByID([1000022,7000008])
        print(parts)

Traceback (most recent call last):
  File "C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py", line 44, in <module>
    getNodeNpArrayFromFile(fileName)
  File "C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py", line 40, in getNodeNpArrayFromFile
    parts=keyWord.get_partByID([1000022,7000008])
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd-0.5.7-py3.6-win-amd64.egg\qd\cae\KeyFile.py", line 105, in get_partByID
    part_id = super(KeyFile, self).get_partByID(*args,**kwargs).get_id()
TypeError: an integer is required (got type list)

**Comment by zhaowei699** [comment]
Hi again
i found my qd version is very old, but how to update to newest version?

I will get this message when I tried to update qd:
>C:\software\anaconda3440\envs\D3plot\python.exe -m pip install qd
Requirement already satisfied: qd in c:\software\anaconda3440\envs\d3plot\lib\site-packages\qd-0.5.7-py3.6-win-amd64.egg
Requirement already satisfied: numpy>=1.11 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: diversipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: scipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from diversipy->qd)

**Comment by qd-codie** [comment]
Hey Wei,
The `KeyFile` class has a binding to query parts from a list but I can't remember which version I added it. I guess you need to update your package in order to use that function.
