### ISSUE TITLE
qd can not work after updating new version

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#28]
**Hi Codie
I meet this error after updating qd:**
C:\software\anaconda3440\envs\D3plot\python.exe C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py
Traceback (most recent call last):
  File "C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py", line 6, in <module>
    from qd.cae.dyna import KeyFile
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\dyna.py", line 4, in <module>
    from .dyna_cpp import *
SystemError: initialization of dyna_cpp raised unreported exception

Process finished with exit code 1

**I updated qd by this method:**
(C:\software\anaconda3440\envs\D3plot) C:\CTC_PrePost_Tool_Qt5>C:\software\anaconda3440\envs\D3plot\python.exe -m pip uninstall qd
Uninstalling qd-0.5.7:
  c:\software\anaconda3440\envs\d3plot\lib\site-packages\qd-0.5.7-py3.6-win-amd64.egg
Proceed (y/n)? y
  Successfully uninstalled qd-0.5.7

(C:\software\anaconda3440\envs\D3plot) C:\CTC_PrePost_Tool_Qt5>C:\software\anaconda3440\envs\D3plot\python.exe -m pip install qd
Collecting qd
  Downloading https://files.pythonhosted.org/packages/ae/9a/489a5c825fae5a1c67564300f15de8d24d5bbb6475dda4e320bf3cb794b5/qd-0.7.2-cp36-cp36m-win_amd64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 327kB/s
Requirement already satisfied: numpy>=1.8 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: diversipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Collecting pybind11>=2.2.0 (from qd)
  Downloading https://files.pythonhosted.org/packages/12/90/0f92a575dc60c8fba6d0c91d6b45abdb1058da9ebed40400cbcfad2ac0a7/pybind11-2.2.3-py2.py3-none-any.whl (144kB)
    100% |████████████████████████████████| 153kB 729kB/s
Requirement already satisfied: h5py in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: scipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from diversipy->qd)
Requirement already satisfied: six in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from h5py->qd)
Installing collected packages: pybind11, qd
Successfully installed pybind11-2.2.3 qd-0.7.2

**Comment by qd-codie** [comment]
Hmmm can you try maybe version 0.6.8 from the dist folder https://github.com/qd-cae/qd-cae-python/tree/master/dist ? Is it working with that older version?

**Comment by zhaowei699** [comment]
Hi Codie
Thanks a lot.
I tried to install 0.6.8 version by these steps:

1.       Uninstall qd by “pip uninstall qd”

2.       Download qd-0.6.8-cp36-cp36m-win_amd64.whl<https://github.com/qd-cae/qd-cae-python/blob/master/dist/qd-0.6.8-cp36-cp36m-win_amd64.whl>

3.       Install by “pip install qd-0.6.8-cp36-cp36m-win_amd64.whl<https://github.com/qd-cae/qd-cae-python/blob/master/dist/qd-0.6.8-cp36-cp36m-win_amd64.whl> ”

It can work for my script with  “from qd.cae.dyna import KeyFile”.

Wei Zhao
Sr. Simulation Engineer
Engineering/Development
wei.zhao@autoliv.com
Mobile: +86-18018673699
Direct: +86-21-69928489

**Comment by qd-codie** [comment]
Hmm okay thanks for the info then it seems the 0.7.2 build is broken on windows for whatever reason. It's always tough to find out remotely why loading a dll is failing. I will recompile 0.7.2 and upload it again, hopefully that works.

**Comment by qd-codie** [comment]
I reuploaded the 0.7.2 built, which Anaconda & Python Version are you using?

**Comment by zhaowei699** [comment]
Thanks a lot, my Python version is 3.6.2.

Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>




***************************************************************
Consider the environment before printing this message.

To read the Companies' Information and Confidentiality Notice, follow this link:
https://www.autoliv.com/autoliv-email-disclaimer
***************************************************************

**Comment by qd-codie** [comment]
Can you maybe later try my reupload (0.7.3) again and tell me whether it works? I updated my Visual Studio Environment a while ago and fear that my compilation requires additional dll's now ...

**Comment by zhaowei699** [comment]
**I have updated it to 0.7.3, but it can't work yet.**
C:\software\anaconda3440\envs\D3plot>C:\software\anaconda3440\envs\D3plot\python.exe -m pip install qd
Collecting qd
  Downloading https://files.pythonhosted.org/packages/4d/b9/669581fdc7079843f96fc450c1e2d8a198ad2afee534a44a0a14fc592b9e/qd-0.7.3-cp36-cp36m-win_amd64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 142kB/s
Requirement already satisfied: h5py in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: pybind11>=2.2.0 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: numpy>=1.8 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: diversipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: six in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from h5py->qd)
Requirement already satisfied: scipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from diversipy->qd)
Installing collected packages: qd
Successfully installed qd-0.7.3

**The error information:**
C:\software\anaconda3440\envs\D3plot\python.exe C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py
Traceback (most recent call last):
  File "C:/CTC_PrePost_Tool_Qt5/Global/DynaCAE.py", line 6, in <module>
    from qd.cae.dyna import KeyFile
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\dyna.py", line 4, in <module>
    from .dyna_cpp import *
SystemError: initialization of dyna_cpp raised unreported exception

Process finished with exit code 1

**Comment by qd-codie** [comment]
Okay guess I have to find a computer around which reproduces the error. Thanks for the test!

**Comment by qd-codie** [comment]
just as an I'm still searching a computer here which can reproduce the error ...

**Comment by zhaowei699** [comment]
Thanks a lot

**Comment by zhaowei699** [comment]
Hi Codie
How about new version 0.8.0?
I used 0.6.8 verison, although it can not support encryption file, I also find other problem.
The error information show that it can not find some nodes, but I can find these nodes by checking key file or opening it by other software. In fact, this model can run very well.


def getNodeNpArrayFromFile(fileName,specifyPartsIDList):
    if os.path.isfile(fileName):
        keyWord=KeyFile(fileName)
        parts=keyWord.get_parts()
        partsIDList=[]
        for part in parts:
            partsIDList.append(part.get_id())
        nodesList = []
        for partID in specifyPartsIDList:
            if partID in partsIDList:
                part=keyWord.get_partByID(partID)
                for node in part.get_nodes():
                    tmp_node=[]
                    tmp_node.append(node.get_id())
                    tmp_node.extend(node.get_coords())
                    nodesList.append(tmp_node)
    nodesArray=np.array(nodesList)
    return nodesArray

Error reading beam in line 5317:invalid stoi argument
Error reading beam in line 5318:Could not find node with id 417342
Error reading beam in line 5319:invalid stoi argument
Error reading beam in line 5320:Could not find node with id 417344
Error reading beam in line 5321:invalid stoi argument
Error reading beam in line 5322:Could not find node with id 417346
Error reading beam in line 5323:invalid stoi argument
Error reading beam in line 5324:Could not find node with id 417348
Error reading beam in line 5325:invalid stoi argument
Error reading beam in line 5326:Could not find node with id 417350
Error reading beam in line 5327:invalid stoi argument
Error reading beam in line 5328:Could not find node with id 417352
Error reading beam in line 5329:invalid stoi argument
Error reading beam in line 5330:Could not find node with id 417354
Error reading beam in line 5331:invalid stoi argument
Error reading shell in line 5333:Could not find node with id 1080
Error reading shell in line 1911458:Could not find node with id 99379625
Error reading solid in line 1913654:Could not find node with id 2
Error reading solid in line 156:Could not find node with id 97321138
Error reading solid in line 68854:Could not find node with id 90000001

**Comment by qd-codie** [comment]
I believe the error is happening while parsing Solids. Unfortunately there are 2 ways to write solid elements in the input file and I had messed up one type (the new one). In newer versions this has been fixed. Btw I just released 0.8.0 which was compiled "the old way" before version 0.7.0. Hopefully this works now. Binary compatability is still tricky for me.

**Comment by zhaowei699** [comment]
Unfortunately,  the V0.8.0 also can't work in my PC. Itried to change "import binout" and "import d3plot", It can't work yet.

**The error:**
  File "C:\CTC_PrePost_Tool_Qt5\Global\DynaCAE.py", line 6, in <module>
    from qd.cae.dyna import KeyFile
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\dyna.py", line 4, in <module>
    from .dyna_cpp import *
SystemError: initialization of dyna_cpp raised unreported exception

(C:\software\anaconda3440\envs\D3plot) C:\CTC_PrePost_Tool_Qt5>C:\software\anaconda3440\envs\D3plot\python.exe -m pip install qd
Collecting qd
  Downloading https://files.pythonhosted.org/packages/a3/53/8aa4a8110fb908c30ede83d8472a128227cf459126719c9875c57865fd31/qd-0.8.0-cp36-cp36m-win_amd64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 14kB/s
Requirement already satisfied: pybind11>=2.2.0 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: h5py in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: diversipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: numpy>=1.8 in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from qd)
Requirement already satisfied: six in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from h5py->qd)
Requirement already satisfied: scipy in c:\software\anaconda3440\envs\d3plot\lib\site-packages (from diversipy->qd)
Installing collected packages: qd
Successfully installed qd-0.8.0

**Comment by qd-codie** [comment]
Hmm I couldn't find any machine yet with this issue, though you are not alone out there with this compatibility problem. Tha's quite annoying since I should be able to figure out the issue quite quickly once I can reproduce the error ....

**Comment by zhaowei699** [comment]
You are right, it is really troublesome problem.
If other windows pc can work well, I will try to re-install my python and qd module and other modules again. I hope it can solve this problem.
In any case, thanks a lot

**Comment by qd-codie** [comment]
Yeah I got another good workaround, I think it is possible to compile it on windows WITHOUT installing Visual Studio, but only Microsoft Build Tools (which are much smaller and lighter), though I need to test it first since some libraries might be missing in this environment.

**Comment by lasso-codie** [comment]
Will be discussed further i #61
