### ISSUE TITLE
Read double precision files

### ISSUE THREAD

**Issue by qd-codie** [qd-cae/qd-cae-python#31]
From Issue #30 

**Detailed Explanation**
When I created the library I did not take double precision files into account, thus they can not be read. I neglected it for a very good reason: When you compute double precision, then dyna also saves the results in double precision (I think they just dump the memory). The additional digits though rarely matter in postprocessing due to the limited numerical precision. 

**Workaround**
You can compute in double precision and write the file in single precision. This also saves you a lot of memory. The additional digits usually do not matter:
 - Inputfile: *DATABASE_FORMAT, IBINARY=1
 - Environment-Variable: export LSTC_BINARY=32ieee
 - Command-line: e. g. ls971 i=input 32ieee=yes

**Fix**
It is relatively simple to extend this, but I'm just too short in time to do this currently. Since you're the second one requiring it, I might raise the priority of this topic now.

**Comment by qd-codie** [comment]
Implement reading of double precision files.

**Comment by nikorose87** [comment]
Hi again,

I did what you said here, but the error was not solved. I am working with the 0.7.4 on CentOS. any suggestion?

**Comment by nikorose87** [comment]
I also tried with 0.8.0 version and It did not work. 
Thanks in advice!

**Comment by qd-codie** [comment]
ok I looked into your file. It indeed is 32 bit, but somehow the file type flag is not set. Also the runtime of your run is not set, which is really weird (as if this stuff was disabled). If I'm right it is a 9.71 file. I need to find a new "database" guide which can hopefully explain this. Maybe it is the solver version which causes this trouble and newer files are different somehow ... I hope they someday abandon this file format for the sake of humanity. 

Anyways I hacked the filetype manually and the reader crashed for anticipating the ending section of the geometry data wrong. I'm not sure what is going on honestly so give me a few days to tap into it. But you are lucky since another person seems to have a similar issue, I will rank it with a high priority.

**Comment by qd-codie** [comment]
If this is your model then it worked.

![image](https://user-images.githubusercontent.com/5020407/44171930-e67c7c00-a0db-11e8-8022-4c326be6a24f.png)

Just kidding, the issue was in the part names section, similar to the mode from the other issue, If you are on windows then you can find [precompiled 0.8.2 windows wheels](https://github.com/qd-cae/qd-cae-python/tree/dev/dist) in the dist folder of the dev branch. On Linux simply clone the [dev branch](https://github.com/qd-cae/qd-cae-python/tree/dev) and compile it yourself. Let me know if it also worked for you.

**Comment by nikorose87** [comment]
Nice, I am gonna try and will tell you. Thanks a lot.

**Comment by nikorose87** [comment]
Hi Codie,

Recently, I used your library again but I am having the same problem mentioned here with version `0.8.6`.

`    d3 = D3plot("d3plot")

RuntimeError: Wrong filetype 538976288 != 1 (or 5) in header of d3plot. Your file might be in Double Precision or the endian of the file is not the endian of the machine.`

I am attaching my files If you want to look at what might be the problem.

https://drive.google.com/file/d/1Sknz1J9-_2nUrHUrnAEXkZMGzwB5-ftr/view?usp=sharing

Hoping you can help me soon.
Regards.

**Comment by nikorose87** [comment]
In addition, the following warning is shown when you use Ipython kernels:

```
/home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.6/site-packages/ipykernel/ipkernel.py:448: DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
  status, indent_spaces = self.shell.input_splitter.check_complete(code)```

**Comment by lasso-codie** [comment]
Looks indeed clearly like a double precision file, which the library can't handle. The warning should not be an issue.
