### ISSUE TITLE
reading displacement and strain from d3plot gives empty list

### ISSUE THREAD

**Issue by TomforGitHub** [qd-cae/qd-cae-python#35]
Hi Codie,

I want to extract strain from d3plot with the following code:

`from qd.cae.dyna import *`
`d3plot = D3plot('d3plot')`
`node = d3plot.get_nodeByID(11)`
`d3plot.read_states('disp')`
`print (node.get_disp())`
`elem = d3plot.get_elementByID(Element.shell, 11)`
`d3plot.read_states('plastic_strain max')`
`print (elem.get_plastic_strain())`

but both `print (node.get_disp())` and `print (elem.get_plastic_strain())` give empty lists:
`[]`
`[]`

Do you have any suggestions about this? Thanks!

**Comment by qd-codie** [comment]
Your code seems fine. Plz run `d3plot.info` and post it here. Also check how many timesteps were recognized by running `d3plot.get_nTimesteps`. Do you have any rigid shells in the model? Just as an info the do not have state data (thank the solver for that confusion).

If you again run version 0.8.0 , it seems it is too unstable and I therefore I took it down again (0.7.3 will be default now). All of my checks run through without an issue.

**Comment by TomforGitHub** [comment]
`>> print (d3plot.info())`
`None`
`>> d3plot.get_nTimesteps()`
`46`

No, there isn't any rigid shell element in the model.

I'll try version 0.7, and update the results.

Thanks!

**Comment by TomforGitHub** [comment]
I just tried version 0.7.3, but the same results occurred like version 0.8.0



发送自 Windows 10 版邮件应用

发件人: Codie (叩地)
发送时间: 2018年7月25日 18:02
收件人: qd-cae/qd-cae-python
抄送: TomforGitHub; Author
主题: Re: [qd-cae/qd-cae-python] reading displacement and strain fromd3plot gives empty list (#35)

Your code seems fine. Plz run d3plot.info and post it here. Also check how many timesteps were recognized by running d3plot.get_nTimesteps. Do you have any rigid shells in the model? Just as an info the do not have state data (thank the solver for that confusion).
If you again run version 0.8.0 , it seems it is too unstable and I therefore I took it down again (0.7.3 will be default now). All of my checks run through without an issue.

**Comment by qd-codie** [comment]
`d3plot.info` should print to the console by itself, you do not need to run print additionally.

That is weird, can you share the model or an example model with me (qd.eng.contact[at]gmail.com)?

**Comment by TomforGitHub** [comment]
I emailed you the model and simulation results.

**Comment by qd-codie** [comment]
Found the bug but didn't fix it entirely yet. The first issue was that the state counter wasn't resetting correctly in your case. I still have a second issue though with the threading queue which I need to fix.

**Comment by qd-codie** [comment]
This is the fixed version (not available yet). It will be in the next release. Let me know whether it worked so I can close the issue.


[qd-0.7.4-cp36-cp36m-win_amd64.zip](https://github.com/qd-cae/qd-cae-python/files/2235215/qd-0.7.4-cp36-cp36m-win_amd64.zip)

**Comment by pmquang87** [comment]
It worked for me. Thank you very much.

**Comment by qd-codie** [comment]
Glad I could help.
