### ISSUE TITLE
RuntimeError: Wrong filetype 538976288 != 1 (or 5) in header of d3plot. Your file might be in Double Precision or the endian of the file is not the endian of the machine.

### ISSUE THREAD

**Issue by pmquang87** [qd-cae/qd-cae-python#36]
Hello,
I am trying to read a d3plot file with the following code:
--
from qd.cae.dyna import D3plot
d3plot = D3plot("C:\\Users\\pmqua\\Documents\\Visual_Studio_Code\\shell_example\\d3plot", read_states=["strain inner"])
node = d3plot.get_nodeByID(11)
d3plot.read_states('disp')
print (node.get_disp())
elem = d3plot.get_elementByID(Element.shell, 11)
d3plot.read_states('plastic_strain max')
print (elem.get_plastic_strain())
--
I am not sure what is wrong and how to solve it. Did anyone see this kind of error before? Thank you. My data files are attachted.
Regards,
Quang

[shell_example.zip](https://github.com/qd-cae/qd-cae-python/files/2235505/shell_example.zip)

**Comment by qd-codie** [comment]
Your file was written with double precision, which the library can not handle. This starts to haunt me since more people simulate with double precision (which is a good thing). There is a trick though to still use the library and compute in double precision. Therefore see issue #31 .

**Comment by pmquang87** [comment]
Thank you for your advice!
