### ISSUE TITLE
ls-prepost does not read the generated nodes.

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#44]
Hi Codie

I was trying your code for creating nodes. However, ls-prepost does not read well the file, it shows something like:
> Warning -Duplicate keyword: NODE input with ID=90

Anyway, your `add_node` command produces 20 digit spaces between end to end number, a well-recognized node list produces 16 spaces between ascii symbols.

Is there any way to solve this?

**Comment by nikorose87** [comment]
[nodes.txt](https://github.com/qd-cae/qd-cae-python/files/2531329/nodes.txt)

**Comment by lasso-codie** [comment]
the formatting is off for whatever reason for the ids (2 chars too much). Should not be difficult to fix. Not sure if the coordinates are fine either.

**Comment by lasso-codie** [comment]
It indeed was a very tiny bug. The initial field size is set to 10 chars for every keyword (also the NODE keyword), but the NODE keyword actually uses 8 and not 10. I updated the dev branch to contain the fix and will include it in the next release.
