### ISSUE TITLE
can not read ‘nodeout_ssd’ from binout

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#45]
code:
from qd.cae.dyna import Binout
file="Y:/cal/01_Comp/16_Noise/099_Interests/03_RHSC/01_Simple_Example_2_Plane/binout"
binout=Binout(file)
allContent=binout.read()
print(allContent)
nodeoutssd=binout.read('nodout_ssd')
print(nodeoutssd)
nfrequency=binout.read('nodout_ssd','nfreq_ssd')
print(nfrequency)
frequency=binout.read('nodout_ssd','frequency')
print(frequency)

error information:
C:\software\anaconda3440\envs\D3plot\python.exe C:/CTC_PrePost_Tool_Qt5/test/readBinout.py
Traceback (most recent call last):
['nodout_ssd']
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 265, in _decode_path
['states', 'title', 'date', 'n_node', 'uid', 'amplitude', 'frequency', 'angle', 'nfreq_ssd', 'version', 'revision']
    dir_symbol = self._get_symbol(self.lsda_root, path)
[200]
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 309, in _get_symbol
    return self._get_symbol(next_symbol, sub_path)
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 307, in _get_symbol
    raise ValueError("Can not find: %s" % next_symbol_name)
ValueError: Can not find: frequency

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/CTC_PrePost_Tool_Qt5/test/readBinout.py", line 10, in <module>
    frequency=binout.read('nodout_ssd','frequency')
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 231, in read
    return self._decode_path(path)
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 276, in _decode_path
    return self._get_variable(path)
  File "C:\software\anaconda3440\envs\D3plot\lib\site-packages\qd\cae\Binout.py", line 358, in _get_variable
    time += subdir_symbol.get(b"time").read()
AttributeError: 'NoneType' object has no attribute 'read'

Process finished with exit code 1

**Comment by zhaowei699** [comment]
I have sent my binout file to "qd.eng.contact@gmail.com". Thanks a lot.
If extract binout file, liking this:
S t e a d y   S t a t e   D y n a m i c s


 nodal print out for frequency =  1.00000E+00

 nodal point      x-disp      y-disp      z-disp       x-vel       y-vel       z-vel      x-accl      y-accl      z-accl
         1-
 amplitude    0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
 angle        0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  1.8000E+02  1.8000E+02  1.8000E+02
         2-
 amplitude    0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00
 angle        0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  0.0000E+00  1.8000E+02  1.8000E+02  1.8000E+02
............

**Comment by lasso-codie** [comment]
谢谢你，我在调试 👍

**Comment by lasso-codie** [comment]
I found the issue. It is a broken assumption of mine:
Usually there is a timestamp for every state written to binout (to know when it occurred). Since variables might be written at different time intervals, I also return the time array when querying a result value.
Your result type does not have a timestamp (since its frequency stuff), therefore the error. I should have it fixed by tomorrow.

**Comment by zhaowei699** [comment]
非常感谢！
Thanks a lot.

**Comment by zhaowei699** [comment]
Hi again
Although you have updated script, but I also can not understand your data structure. From the binout which I have sent to you, there are 200 frequency and there are 857 nodes under one frequency. Why the shape of ‘amplitude’ and ‘angle’ are (200,7713). I think the structure should be liking this:
amplitude[0]save all nodes displacement in first frequency. amplitude[0][0]save first node displacement under first frequency.


For example:
amplitude=binout.read('nodout_ssd','amplitude')
print(amplitude.shape)
print(amplitude[0].shape)
angle=binout.read('nodout_ssd','angle')
print(angle[0])

Result:
(200, 7713)
(7713,)
[  0.   0. 180. ...   0.   0. 180.]

**Comment by zhaowei699** [comment]
Of course, I can use "angle.shape=200,875,9" to meet my request. Thanks a lot.

**Comment by lasso-codie** [comment]
Hi Zhao,
the structure of the arrays is not specified by me, is the structure given by LS-Dyna, though I can rearrange during reading. I must admit I only tested whether it worked and not took a closer look at the data within the arrays since I don't know the output type thus I didn't know what to expect. But thanks for your information, I will take it into consideration.
