### ISSUE TITLE
d3plot timestep array contains only zeros

### ISSUE THREAD

**Issue by df0815** [qd-cae/qd-cae-python#46]
version: 0.8.5 (master)
Python 3.6.8 on CentOS7 with gcc 6.3.1

in the latest master version, when reading the time steps, the resulting array is completely zero, i.e.

from qd.cae.dyna import D3plot
d3 = D3plot("d3plot")
st = d3.get_timesteps()
print(st)

-> [0. 0. 0. 0. ...]

The same problem occurs when using the pure C++ code.
Any idea?

Great lib btw. I was waiting a long time for this. Thanks to all of you
Dirk

**Comment by lasso-codie** [comment]
Hi,
seems I messed up somewhere. For once in a while I'm also to reproduce. Should not be that much of an issue to fix ... hopefully.

**Comment by lasso-codie** [comment]
My tests ran through since they mostly test on femzipped files, which are fine. There is always a loophole ...

**Comment by lasso-codie** [comment]
Ok I found the issue and it was pretty severe. Therefore I will make a version 0.8.6 today which contains the fix.

**Comment by df0815** [comment]
Great, seems to work now with 0.8.6. Thanks a lot!

**Comment by lasso-codie** [comment]
I see you found the package before I could release it 😛
