### ISSUE TITLE
Problem with double precision files

### ISSUE THREAD

**Issue by krobolus** [qd-cae/qd-cae-python#47]
Hello everyone, 
it looks like some other people had problems with reading double precision output files as well (#31  ; #36 ). My problem with the given workaround is, that I do not have the possibility to redo the simulations with single precision output. 
Is there any possibility to read double precision files, or convert double precision files to single precision files?

Regards,
Julian

**Comment by lasso-codie** [comment]
No there is no workaround yet. About how many simulations are we talking?

**Comment by krobolus** [comment]
About 300

**Comment by lasso-codie** [comment]
Hmmm, there is a way to get your hands on the data if you really need it, but it is unrelated to this lib, thus I would prefer discussing it via mail (qd.eng.contact@gmail.com). Send me a message and I will explain it 2 u in details.
