### ISSUE TITLE
Not able to read information in keyfile

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#49]
Hey Codie,

I was able to read a keyfile and their respective keys, however when I want to `get_nParts` It shows a zero 0, which is not true. I also aligned the keywords in order to see if the problem would be the document itself, but It was not.

Can you help me to read the correct number of parts on the file attached?
[main0.zip](https://github.com/qd-cae/qd-cae-python/files/2992500/main0.zip)

**Comment by lasso-codie** [comment]
Hey Niko,
have you tried to enable mesh parsing? Otherwise the file is just treated as text without creating the mesh database.

```python
>>> kf = KeyFile("main0.key", parse_mesh=True)
>>> kf.get_nParts()
78
```

For me the code works.

**Comment by nikorose87** [comment]
Dear God, Thanks!
Yeah, I did not parse the keyfile.
