### ISSUE TITLE
ImportError Numpy

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#50]
hi Codie

I updated your package, but this error is shown:

`ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['E:\\ProgramData\\Anaconda3\\envs\\dynaenv\\lib\\site-packages\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.`

I have numpy version 1.15.1

Which version do you think I Should downgrade?

Thanks

**Comment by lasso-codie** [comment]
I'm not familiar with this error. Hmm either during installation/compilation or during runtime you have multiple numpy installations in your system environment paths. Or maybe pip did install another numpy version but that would be weird without removing the old one. For 3.7 I'm using 1.15.2 and 3.6 I have 1.15.4.

**Comment by nikorose87** [comment]
Thanks, I could solve it!
