### ISSUE TITLE
Reading infinitesimal strains from D3plot files

### ISSUE THREAD

**Issue by MisterBinh** [qd-cae/qd-cae-python#54]
Hello everyone, 

when trying to read infinitesimal strains from d3plot files with

d3plot = D3plot('some_file', read_states=['strain'])

 I would get the message: "Unable to read strains, since there are none". Even though, the strains have to be in the d3plot file because I can read with LS-Prepost.
Does the read_states option exclude "infinitesimal strains"?

Best regards,
Binh

**Comment by MisterBinh** [comment]
Sorry for the late response but I have found the error. Apparently, the strain was saved as a plastic strain and I have to apply the read_states=['plastic_strain'] flag. 

But one question arises, is there a reason why one has to separate specifically plastic strain and its "normal" strain?

**Comment by lasso-codie** [comment]
It's two different fields thus it saves memory and time to load only one. Also the strain tensor is defined with 6 entries, whereas the plastic strain is of course the "effective" plastic strain, thus the plastic strain tensor was squished to a scalar, so these two are quite different. I think they do it to prevent reverse-engineering of materials.
