### ISSUE TITLE
some binout name liking "binout0000%001"

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#55]
Hi Codie
I found if the binout0000 file is enough big, the dyna solver will create new binout file liking "binout0000%001","binout0000%002", and so on. 
Do you also cover these files in your scripts?

Liking the following error, I think your script miss these files with "%":
File "main.py", line 73, in main
    Wad=getWAD(os.path.join(root,file))
  File "main.py", line 82, in getWAD
    nodeIdArray, xyzCoordArray=getNodeIdAndCoordsAtSomeTime(binoutName, contactId)
  File "C:\Calculate_WAD\binout_function.py", line 30, in getNodeIdAndCoordsAtSomeTime
    XCoordsArray=binout.read('nodout',"x_coordinate")[minIndex,:].reshape(-1,1)
IndexError: index 1340 is out of bounds for axis 0 with size 501

**Comment by lasso-codie** [comment]
The internal code is from LSTC and I don't think that they cover this use-case. Though I usually experienced that ls-dyna splits rather the dataseries across these different binouts. E.g. nodout is put into another binout than matsum. Do I understand it correctly that in your case the datapoints itself are split?

**Comment by zhaowei699** [comment]
I think you are right.
If we had some keys to set and avoid output binout data liking "binout0000%001", it is better. But I can't find it.

**Comment by lasso-codie** [comment]
You can read these binouts one at a time as a circumvention then. I don't know if I should read all at once since it might increase loading time severly in certain cases.

**Comment by zhaowei699** [comment]
How to read all binouts at a time?

**Comment by lasso-codie** [comment]
Simply open binout0001 and binout0002 seperately

**Comment by zhaowei699** [comment]
I think it hard for me. Because it looks only nodeout were split to different files. the rcforce is ok. 

see my codes, I am success to get rcforce, but nodeout can't get correctly. When I get contact time and line index at this time, I try to get the same line index for nodeout, it can't.

def getNodeIdAndCoordsAtSomeTime(binoutName, contactId):
    binout=Binout(binoutName)
    print(binout.filelist)
    # get the contact time or min index
    timeArray=binout.read('rcforc','time')
    idsArray = binout.read('rcforc', 'ids')
    contactIndex = np.argwhere(idsArray == contactId)[0]
    xforceArray=binout.read('rcforc','x_force')[:,contactIndex[0]]
    yforceArray=binout.read('rcforc','y_force')[:,contactIndex[0]]
    zforceArray=binout.read('rcforc','z_force')[:,contactIndex[0]]
    xNonzeroforceIndex = np.argwhere(xforceArray != 0.0)
    yNonzeroforceIndex = np.argwhere(yforceArray != 0.0)
    zNonzeroforceIndex = np.argwhere(zforceArray != 0.0)
    #print(xNonzeroforceIndex.size,xNonzeroforceIndex)
    if xNonzeroforceIndex.size!=0 and yNonzeroforceIndex.size!=0 and zNonzeroforceIndex.size!=0:
        xNonzeroforceIndex = xNonzeroforceIndex[0, 0]
        yNonzeroforceIndex = yNonzeroforceIndex[0, 0]
        zNonzeroforceIndex = zNonzeroforceIndex[0, 0]
        minIndex=min(xNonzeroforceIndex,yNonzeroforceIndex,zNonzeroforceIndex)
        contactTime=timeArray[minIndex]
        print("get contact time ",contactTime)

        # get all node coords at contact time
        nodeIdArray=binout.read('nodout',"ids")
        XCoordsArray=binout.read('nodout',"x_coordinate")[minIndex,:].reshape(-1,1)
        YCoordsArray=binout.read('nodout',"y_coordinate")[minIndex,:].reshape(-1,1)
        ZCoordsArray=binout.read('nodout',"z_coordinate")[minIndex,:].reshape(-1,1)

        xyzCoordArray=np.hstack((XCoordsArray, YCoordsArray,ZCoordsArray))
        #print(xyzCoordArray[0:10])
        return nodeIdArray,xyzCoordArray
    else:
        return np.array([]),np.array([])

**Comment by lasso-codie** [comment]
Hmmm just as an intermediate question, is the nodout written with the same time frequency as the rcforc file? This might also cause such an issue.

**Comment by zhaowei699** [comment]
Thanks a lot, we found the reason. The time frequency is different between rcforce and nodeout in my model.

**Comment by lasso-codie** [comment]
Glad that I could help 👍 It's a subtle but common issue.
