### ISSUE TITLE
glibgc problem

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#56]
Hi Qd

Recently, I could configured and run the test on servers, however when I run the script, the following error is shown:

`*** glibc detected *** python: free(): invalid pointer: 0x00007f06132aeaa0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e5e)[0x7f061a80fe5e]
/lib64/libc.so.6(+0x78cad)[0x7f061a812cad]
/gpfs/home/e/p/eprietop/Karst/anaconda3/envs/dynaenv/bin/../lib/libstdc++.so.6(_ZNSs7reserveEm+0x50)[0x7f061320de50]
/N/u/eprietop/Karst/anaconda3/envs/dynaenv/lib/python3.6/site-packages/qd-0.8.8-py3.6-linux-x86_64.egg/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so(+0x7e907)[0x7f05ef485907]
/N/u/eprietop/Karst/anaconda3/envs/dynaenv/lib/python3.6/site-packages/qd-0.8.8-py3.6-linux-x86_64.egg/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so(+0x9cb82)[0x7f05ef4a3b82]
/N/u/eprietop/Karst/anaconda3/envs/dynaenv/lib/python3.6/site-packages/qd-0.8.8-py3.6-linux-x86_64.egg/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so(+0x47d27)[0x7f05ef44ed27]
/N/u/eprietop/Karst/anaconda3/envs/dynaenv/lib/python3.6/site-packages/qd-0.8.8-py3.6-linux-x86_64.egg/qd/cae/dyna_cpp.cpython-36m-x86_64-linux-gnu.so(PyInit_dyna_cpp+0x45)[0x7f05ef45a545]
python(_PyImport_LoadDynamicModuleWithSpec+0x185)[0x5578f84bb335]
python(+0x217540)[0x5578f84bb540]
python(PyCFunction_Call+0x131)[0x5578f83b8711]
` 

I realized that the package is in conflict with the [gmsh](https://pypi.org/project/gmsh-sdk/) package, can you give me an advice of what can be happening?

**Comment by lasso-codie** [comment]
Hard to tell what is going on from that trace. It might be a bug or incompatible versions of glibc. Second is related to how you configured your OS. If you have a conflict in glibc versions you can recompile qd to the same version of glibc as gmsh.

Also note if you require a pure-python library with similar (though not identical) functionality, take a look at our new [lasso-python](https://github.com/lasso-gmbh/lasso-python) library.

**Comment by nikorose87** [comment]
Thanks man!
