### ISSUE TITLE
Test failed after installing with anaconda

### ISSUE THREAD

**Issue by nikorose87** [qd-cae/qd-cae-python#57]
Hi Codie
This time I have got this error:

> ImportError: cannot import name 'QD_D3plot' from 'qd.cae.dyna_cpp' (unknown location)

I built a new env with the following packages:

`conda install -y pandas scipy matplotlib pybind11 numpy xlrd
#pip install --upgrade gmsh-sdk
pip install geomdl
conda install -y scikit-learn 
conda install -y bokeh 
conda install -y pydy 
conda install -y seaborn
conda install -c selenium
conda install -c conda-forge pagmo`

Installation was done normally, however, when testing this message is shown:

`FEMZIP library not found. Compiling without FEMZIP.
running test
Searching for pybind11==2.1.1
Best match: pybind11 2.1.1
Processing pybind11-2.1.1-py3.7.egg

Using /home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/site-packages/pybind11-2.1.1-py3.7.egg
/home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Module pybind11 was already imported from /home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/site-packages/pybind11/__init__.py, but /home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/site-packages/pybind11-2.1.1-py3.7.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running egg_info
writing qd.egg-info/PKG-INFO
writing dependency_links to qd.egg-info/dependency_links.txt
writing requirements to qd.egg-info/requires.txt
writing top-level names to qd.egg-info/top_level.txt
reading manifest file 'qd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'qd.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/qd/cae/dyna_cpp.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so -> qd/cae
test_dyna (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_dyna (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dyna
Traceback (most recent call last):
  File "/home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/nikorose/Workspace/anaconda3/envs/dynaenv/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/nikorose/Downloads/qd-cae-python/test/test_dyna.py", line 12, in <module>
    from qd.cae.dyna import *
  File "/home/nikorose/Downloads/qd-cae-python/qd/cae/dyna.py", line 8, in <module>
    from .D3plot import D3plot
  File "/home/nikorose/Downloads/qd-cae-python/qd/cae/D3plot.py", line 4, in <module>
    from .dyna_cpp import QD_D3plot, QD_Part
ImportError: cannot import name 'QD_D3plot' from 'qd.cae.dyna_cpp' (unknown location)

----------------------------------------------------------------------
Ran 1 test in 0.000s
`
I have used this envs in other PCs and none problems were generated.

Regards

**Comment by lasso-codie** [comment]
Hmm never saw one of those. Is in the folder `/home/nikorose/Downloads/qd-cae-python/qd/cae/` a `dyna_cpp` file (most probably with a much longer and complicated name)?

**Comment by nikorose87** [comment]
There is a file called: 

> dyna_cpp.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so

**Comment by lasso-codie** [comment]
sry for the late response, it looks fine from that point of view. Did you compile it on the same machine?

**Comment by nikorose87** [comment]
I built a new environment in order to see If there were any incompatibility with another package, It seems that the [pagmo](https://esa.github.io/pagmo2/index.html) shows conflict with the QD library. 
Regards.

**Comment by lasso-codie** [comment]
hmmm really wondering what they do. Maybe they ship some incompatible standard libs. Thanks anyways for finding this troublesome issue.
