### ISSUE TITLE
Issue w/ compiling on RHEL 7

### ISSUE THREAD

**Issue by eltatio** [qd-cae/qd-cae-python#62]
I have issues w/ compilation on RHEL 7 and anaconda/python 3

Below some of the errors preventing proper compilation : 

/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:317:5: erreur: ‘is_trivially_copyable’ is not a member of ‘std’
     std::is_trivially_copyable<T>,
     ^
/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:317:5: erreur: ‘is_trivially_copyable’ is not a member of ‘std’
/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:317:33: erreur: patron de l'argument 2 est invalide
     std::is_trivially_copyable<T>,
                                 ^
/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:949:49: erreur: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                 ^
/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:949:49: erreur: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
/local/laurent/anaconda3/include/python3.7m/pybind11/numpy.h:949:72: erreur: patron de l'argument 1 est invalide
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {

gcc version : 
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

Thanks for hint to correct.

Laurent.

**Comment by lasso-codie** [comment]
Hmm obviously an issue with pybind11. For a quick fix gcc5 should work and I will check it myself more thoroughly.

**Comment by eltatio** [comment]
Hello Codie,
Thanks for support
Finally it worked with g++-5 👍
In the mean Time we tested also lasso with simple models.
Did you also consider the possibility to write d3plot files?
If not, would it be possible to develop this as a service  ?

Thanks by avance

Laurent Guérin...

Le jeu. 24 oct. 2019 à 14:15, Codie (蒂诺) <notifications@github.com> a
écrit :

**Comment by lasso-codie** [comment]
Hey Laurent,
it indeed would be possible for me to implement a d3plot writer. We didn't need it yet but if you are seriously interested you can contact me under [codie@lasso.de](mailto:codie@lasso.de).

I will leave the issue open since it ought to compile under gcc 4.8. My guess is the installation process somehow used a newer pybind11 version which now requires at least gcc5 or to be more precise the c++14 standard.
