### ISSUE TITLE
Installation error: pip.main

### ISSUE THREAD

**Issue by orpharion** [qd-cae/qd-cae-python#63]
Installation fails if pybind11 not installed, as pip.main has been deprecated and cannot be used to install it. Perhaps it would be better to list pybind11 as a requirement rather than attempting to install it in setup? Installation succeeded once pybind11 was installed.

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\alex.deoliveira\Programs\anaconda3_32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ALEX~1.DEO\\AppData\\Local\\Temp\\pip-install-wmr88fu2\\qd\\setup.py'"'"'; __file__='"'"'C:\\Users\\ALEX~1.DEO\\AppData\\Local\\Temp\\pip-install-wmr88fu2\\qd\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\ALEX~1.DEO\AppData\Local\Temp\pip-install-wmr88fu2\qd\
    Complete output (12 lines):
    Traceback (most recent call last):
      File "C:\Users\ALEX~1.DEO\AppData\Local\Temp\pip-install-wmr88fu2\qd\setup.py", line 12, in <module>
        import pybind11
    ModuleNotFoundError: No module named 'pybind11'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ALEX~1.DEO\AppData\Local\Temp\pip-install-wmr88fu2\qd\setup.py", line 15, in <module>
        pip.main(['install', 'pybind11==2.1.1'])
    AttributeError: module 'pip' has no attribute 'main'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lasso-codie** [comment]
Agreed the issue was at that time that I need to call a pybind11 function before the `setup` function. There is a quick fix though which I found [here](https://github.com/pybind/python_example/blob/master/setup.py):

```python
class get_pybind_include(object):
    """Helper class to determine the pybind11 include path
    The purpose of this class is to postpone importing pybind11
    until it is actually installed, so that the ``get_include()``
    method can be invoked. """

    def __init__(self, user=False):
        self.user = user

    def __str__(self):
        import pybind11
        return pybind11.get_include(self.user)
```
