### ISSUE TITLE
Can there any method to control LS-DYNA from python?

### ISSUE THREAD

**Issue by awecefil** [qd-cae/qd-cae-python#64]
Hi, thank you for giving such a powerful API to read KeyFile, D3plot.

However, I have a problem about how to control LS-DYNA automatically? Because I want to change run many experiments in LS-DYNA.

For example, I want to input a .k file into the LS-DYNA solver automatically by python or other 
programming language, but I can't find how to do it.

As I know, Ansys can use python to do this thing. So, is there any method can do this thing?

**Comment by lasso-codie** [comment]
The library can't but you can of course use python to start the ls-dyna solver process in the background and control the process itself through the process handle.
