### ISSUE TITLE
PartKeyword ignores additional data

### ISSUE THREAD

**Issue by lasso-codie** [qd-cae/qd-cae-python#66]
Adding parts with (add_part()) doesn’t include the additional_card_data, I can index to it but not print it in the final k-file. 

```python
>>># create file with mesh parsing on
>>> kf = KeyFile(parse_mesh=True)
>>> # create a new part keyword
>>> kw = kf.add_keyword("*PART")
>>> # secid and mid for part
>>> additional_data = "   2000001   2000017"
>>> part = kw.add_part(100, "my_part", additional_data)
>>> print(kw)
*PART
                                                               my_part
       100
>>>kw[0,1]
2000001
```

**Comment by speculator9** [comment]
Happens when pid > 20. For example if you run the loop below it will add the data till pid =20

>>>additional_data = "   2000001   2000017"
>>>file = KeyFile(parse_mesh=True)
>>>kw =file.add_keyword("*Part")
>>>for id in range(0,40):
    kw.add_part(id, str(id), additional_lines= additional_data)

**Comment by lasso-codie** [comment]
Took me almost a day but fixed it. Unfortunately it broke treatment of special keyword cases such as *PART_INERTIA. I must admit I programmed it not very well due to the limited time I had back then, but also right now I barely find time to fix more severe issues like this.

**Comment by speculator9** [comment]
Thank You codie! unfortunately I dont really know C++ and could not do much in helping out but let me know if there is anything else I can help you with. Many thanks. Stay Safe
