### ISSUE TITLE
Could not import C++ Submodule dyna_cpp with error message

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#67]
I install qd by "pip install qd", but i get the following error: 

File "C:\my_env_python\ICCoverage\lib\site-packages\qd\cae\dyna.py", line 7, in <module>
    "Could not import C++ Submodule dyna_cpp with error message: %s." % str(err))
ImportError: Could not import C++ Submodule dyna_cpp with error message: DLL load failed: The specified module could not be found..

**Comment by lasso-codie** [comment]
Hmm some dependency dlls are missing on your system. Debugging this is usually harder. Try installing the intel libraries with conda, this fixes it most of the time:

```bash
conda install icc_rt mkl
```

**Comment by zhaowei699** [comment]
Thanks, I will install conda to try.

This is my the whole installing progress, maybe it can't work by "virtualenv ":

C:\software\cmder_mini
λ cd \my_env_python\

C:\my_env_python
λ C:\Python36\Scripts\virtualenv qd_dyna
Using base prefix 'c:\\python36'
New python executable in C:\my_env_python\qd_dyna\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

C:\my_env_python
λ qd_dyna\Scripts\activate.bat

C:\my_env_python
(qd_dyna) λ pip install qd==0.8.9
Collecting qd==0.8.9
  Using cached qd-0.8.9-cp36-cp36m-win_amd64.whl (2.8 MB)
Collecting numpy>=1.8
  Using cached numpy-1.18.4-cp36-cp36m-win_amd64.whl (12.8 MB)
Collecting pybind11==2.1.1
  Using cached pybind11-2.1.1-py2.py3-none-any.whl (109 kB)
Collecting h5py
  Using cached h5py-2.10.0-cp36-cp36m-win_amd64.whl (2.4 MB)
Processing c:\users\wei.zhao\appdata\local\pip\cache\wheels\d5\30\66\06db3a9eebd027893d85753ed70c6d16eb9eef432946e36a96\diversipy-0.8-py3-none-any.whl
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting scipy
  Using cached scipy-1.4.1-cp36-cp36m-win_amd64.whl (30.8 MB)
Installing collected packages: numpy, pybind11, six, h5py, scipy, diversipy, qd
Successfully installed diversipy-0.8 h5py-2.10.0 numpy-1.18.4 pybind11-2.1.1 qd-0.8.9 scipy-1.4.1 six-1.14.0

C:\my_env_python
(qd_dyna) λ python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qd.cae.dyna import KeyFile
Traceback (most recent call last):
  File "C:\my_env_python\qd_dyna\lib\site-packages\qd\cae\dyna.py", line 4, in <module>
    from .dyna_cpp import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\my_env_python\qd_dyna\lib\site-packages\qd\cae\dyna.py", line 7, in <module>
    "Could not import C++ Submodule dyna_cpp with error message: %s." % str(err))
ImportError: Could not import C++ Submodule dyna_cpp with error message: DLL load failed: The specified module could not be found..
>>>

**Comment by lasso-codie** [comment]
only if the dlls are not available in the virtual environment but conda should be able to install them into the virtualenv

**Comment by zhaowei699** [comment]
Hi Codie
I am still troubled by this problem.

see the following picture:
1. with conda env (It is ok)
![with_conda](https://user-images.githubusercontent.com/30488215/82291721-1b69e100-99dc-11ea-8777-729b8af5babd.PNG)
2. no conda env
![no_conda](https://user-images.githubusercontent.com/30488215/82291750-26bd0c80-99dc-11ea-924e-192d8cf6b4d9.PNG)

Even though I'm using the same python path, it will show error if I want to run the script by os.system(../python.exe  some_script_with_**qd**.py).
Any sugestions are welcome.
