### ISSUE TITLE
Is it possible to get discrete elements

### ISSUE THREAD

**Issue by zhaowei699** [qd-cae/qd-cae-python#68]
This is my keyword:

> *ELEMENT_DISCRETE
>        1      12     264       1                      0.       0              0.
>        2      13   44038       3                      0.       0              0.

I want to get these elements by the following code:
**But Discrete is not the Beam**
```
        for element in keyfile_obj.get_elements(Element.beam):
            node_list = element.get_nodes()
```

**Comment by lasso-codie** [comment]
Is it "Discrete Element Sphere" (DES). At least thats the only thing I find in the docs referring to "discrete".

**Comment by zhaowei699** [comment]
No, it is only spring element. 
Using to define a discrete (spring or damper) element between two nodes

![spring](https://user-images.githubusercontent.com/30488215/81517074-4ca73900-936c-11ea-81f1-86e779ab90f4.PNG)

**Comment by lasso-codie** [comment]
Hmmm in the file format there is no element type "spring/damper/discrete". Just 1D, 2D and 3D so I guess in 1D the springs are already contained, which I mistook as beams.

There is a way to filter them out though. In the [lasso-python](https://github.com/lasso-gmbh/lasso-python) there is an array for the [material type number of parts](https://lasso-gmbh.github.io/lasso-python/build/html/dyna/ArrayType.html#lasso.dyna.ArrayType.ArrayType.part_material_type). Every entry in there is the material number, e.g. 20 for MAT20.

**Comment by zhaowei699** [comment]
I think it is very hard for me to test and study new module. I prefer to read keyfile directly by file.open(). 
If you can fix this problem, I can waiting several weeks.
Thanks a lot

**Comment by lasso-codie** [comment]
Ah I see it's for the `KeyFile` class not `D3plot`

**Comment by zhaowei699** [comment]
yes，this time, I only read key-file.

**Comment by zhaowei699** [comment]
Hi Codie
I only want to confirm whether you will plan to read discrete(spring) element for KeyFile?

**Comment by lasso-codie** [comment]
I have currently no plan when to implement this, since this library is maintained for primarily bugfixes. I will leave this issue open though, also since the effort to implement this should be limited

**Comment by zhaowei699** [comment]
Thanks a lot, in any case, it is perfect package for me.
