### ISSUE TITLE
Memory issues when d3plot file is in GBs

### ISSUE THREAD

**Issue by ArvindSharda78** [qd-cae/qd-cae-python#69]
When a d3plot file which is huge (including all other d3plot files) mean to say it can >1GB, then reading call itself gives memory issue. Can you please check it
Regards
Arvind

**Comment by lasso-codie** [comment]
Yeah I know of this limitation, it's due to the object orientation. That is why we rewrote qd in [lasso-python](https://github.com/lasso-gmbh/lasso-python). In lasso-python a D3plot consumes the same memory as the basic files have and there are even options to reduce the consumption further. The lasso-python d3plot reader is based solely on arrays. It's crazy fast but also more uncomfortable in usage (filtering elements of parts etc.). Maybe check it out.

**Comment by ArvindSharda78** [comment]
Thanks for the quick response,
I tried Lasso-python too, but there as well i got memory issue. any way to avoid it .

**Comment by lasso-codie** [comment]
Use the arguments `n_files_to_load_at_once` and `state_array_filter` in the constructor in lasso python d3plot to reduce the memory consumption.

```python
from lasso.dyna import D3plot, ArrayType
d3plot=D3plot(
  "path/to/d3plot",
  n_files_to_load_at_once=1,
  state_array_filter=[ArrayType.node_displacement]
)
```

We never had any issues ever since we filter results and pull files one by one into memory.

**Comment by ArvindSharda78** [comment]
Thanks again for this input, I had tried it as well reading the documentation. I tried it again and got the following error.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0765dbbb9388> in <module>
      1 from lasso.dyna import D3plot, ArrayType
----> 2 d3plot=D3plot(
      3   "d3plot",
      4   n_files_to_load_at_once=1,
      5   state_array_filter=[ArrayType.node_displacement]

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lasso\dyna\D3plot.py in __init__(self, filepath, use_femzip, n_files_to_load_at_once, state_array_filter)
    133 
    134         # State Data
--> 135         self._read_states()
    136 
    137     @property

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lasso\dyna\D3plot.py in _read_states(self)
   2054         # arrays need to be preallocated if we transfer them
   2055         if transfer_arrays:
-> 2056             self._read_states_allocate_arrays(
   2057                 n_states, self.state_array_filter, self.arrays)
   2058 

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lasso\dyna\D3plot.py in _read_states_allocate_arrays(self, n_states, array_names, array_dict)
   1843 
   1844             if array_name in state_array_shapes:
-> 1845                 array_dict[array_name] = np.empty(
   1846                     state_array_shapes[array_name], dtype=array_dtype)
   1847             else:

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

**Comment by lasso-codie** [comment]
Lets continue by mail (codie@lasso.de) since it is not related to qd anymore, but looks like the numpy array is too big for memory? Do you use a 32bit installation or computer?

**Comment by ArvindSharda78** [comment]
> Lets continue by mail ([codie@lasso.de](mailto:codie@lasso.de)) since it is not related to qd anymore, but looks like the numpy array is too big for memory? Do you use a 32bit installation or computer?

Sure!
