### ISSUE TITLE
Element thickness and material density

### ISSUE THREAD

**Issue by OxygenLiu** [qd-cae/qd-cae-python#73]
I couldn't figure out how to read element thickness and material density from a KeyFile. 

Any ideas are greatly appreciated!

**Comment by lasso-codie** [comment]
They are usually stored in the *PART keyword aren't they?

**Comment by OxygenLiu** [comment]
Not directly, material density is under  *MAT keyword,  and thickness is stored in *SECTION keyword. 

OK, I realized that qd.cae.dyna does not support *MAT and *SECTION.  Will it be implemented in lasso.dyna?

**Comment by OxygenLiu** [comment]
OK, figured it out.  Assuming we want to find out the material density and thickness of Part 2000166, the following code works, but a bit lousy.  I would expect something simpler.  Any suggestions? 

```python 
partid = 2000166
partkw = keyfile['*PART']
for _ in range(len(partkw)):
    if partkw[_].get_card_valueByName('pid') == partid:
        matid = partkw[_].get_card_valueByName('mid')
        secid = partkw[_].get_card_valueByName('secid')

matkw = keyfile['*MAT_PIECEWISE_LINEAR_PLASTICITY']
for _ in range(len(matkw)):
    if matkw[_].get_card_valueByName('mid') == matid:
        ro = matkw[_].get_card_valueByName('ro')
        
seckw = keyfile['*SECTION_SHELL']
for _ in range(len(seckw)):
    if seckw[_].get_card_valueByName('secid') == secid:
        t1 = seckw[_].get_card_valueByName('t1')
```
