### ISSUE TITLE
femunzip

### ISSUE THREAD

**Issue by antahia** [qd-cae/qd-cae-python#75]
**Is your feature request related to a problem? Please describe.**
I would like to read the d3plot.fz file

**Describe the solution you'd like**
I would like to be able to install the femzip reader with just javing the femunzip.

**Comment by lasso-codie** [comment]
Why don't you just use the femunzip command line tool from the official femzip distribution?

**Comment by antahia** [comment]
I think you mean to femunzip the files and then read the d3plot with qd or? 
As much as I know reading femunzip directly is faster than reading d3plot. that is why ...

**Comment by lasso-codie** [comment]
The precompiled version distributed through pip can already read femzipped files directly. In the docs of the [D3pot](https://qd-cae.github.io/qd-cae-python/build/html/qd_cae_dyna_D3plot.html#qd.cae.dyna.D3plot) class there is an argument called `use_femzip`. Simply set it to `true`.

**Comment by antahia** [comment]
I think you have not understood my problem, 
If I do so I will get the error that the femzip is not installed, I have set the path to femuzip dir, but since I don't have femzip it seems it is still skipping to install it.

**Comment by lasso-codie** [comment]
Okay so I assume you set the femzip path in the top of the `setup.py` file and it is still compiling without femzip when you install it manually. Am I correct?

**Comment by antahia** [comment]
I set the path just for femuzip, and it is still compiled without femzip. 

I think the problem is that I don't have femzip path.

**Comment by lasso-codie** [comment]
If you want to compile with femunzip then you need to give a path not just to femunzip itself, but to a folder containing the libraries provided by femzip. There is a small guide to this in the docs [here](https://qd-cae.github.io/qd-cae-python/build/html/compilation_guide.html#compilation-with-femzip-support).

**Comment by antahia** [comment]
I have followed that and it didn't work, can it be due to this that first I installed it without that path? I tried to reinstall it, but still doesn't work

**Comment by lasso-codie** [comment]
No but just as a hint you can uninstall the old version by running:

```
python -m pip uninstall qd
```

when it starts does the command line print: `FEMZIP library not found. Compiling without FEMZIP`?

**Comment by antahia** [comment]
to your first question, yes, I get that 
![grafik](https://user-images.githubusercontent.com/67968562/98809886-9a395700-241e-11eb-85cb-1257b979d37d.png)

this is how it looks on setup.py
![grafik](https://user-images.githubusercontent.com/67968562/98810013-cd7be600-241e-11eb-9d3a-f9f343e53be4.png)

this is the file structure,
![grafik](https://user-images.githubusercontent.com/67968562/98810434-8b9f6f80-241f-11eb-8fa4-6376273f2246.png)

and in my lib, I don't see `libfemunzip*`. Can it be due to dyna version? whcih dyna version are you using?

**Comment by lasso-codie** [comment]
As I stated in the [Docs](https://qd-cae.github.io/qd-cae-python/build/html/compilation_guide.html#compilation-with-femzip-support), you need to download it yourself from [Sidact](https://www.sidact.de/). Since I guess you don't have access, I will send you a mail with a download link from our server later.
By the way, think about using [lasso-python](https://github.com/lasso-gmbh/lasso-python), it can also read femzipped files directly and doesn't need compilation.

**Comment by antahia** [comment]
I have downloaded the femunzip from the sidact page.

I will look into lasso-python, didn't know about it.
