### ISSUE TITLE
Node Coordinates of D3plot are wrong when using C++ version

### ISSUE THREAD

**Issue by PucklaMotzer09** [qd-cae/qd-cae-python#76]
**Describe the bug**
I want to use the C++ interface of ```qd/cae/dyna_cpp```, but when reading the coordinates, they are wrong. The x and y coordinates are something completely different, but the z coordinate is correct. I tried to do the same using the python interface and it confirms exactly that. Using the python interface everything works as it should.<br>
I also tried to read the displacements and they are completely correct.

**To Reproduce**
C++ code:
```c++
std::unique_ptr<qd::D3plot> d3plot = std::make_unique<qd::D3plot>(d3plot_path, "disp");
const auto part = d3plot->get_partByID(PART_ID);
const auto nodes = pouch->get_nodes();
std::cout << "Nodes: " << std::endl;
std::cout << std::fixed << std::setprecision(3);
for (const auto n : nodes) {
    const auto& coords = d3plot->get_nodeByID(n)->get_coords()[30];
    std::cout << n->get_nodeID() << ": (" << coords[0] << "; " << coords[1] << "; " << coords[2] << "), ";
}
std::cout << std::endl;
```

**Expected behavior**
The coordinates should be the same as in the python version.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Browser: Mozilla Firefox
 - Version: 0.8.9

**Comment by PucklaMotzer09** [comment]
I found the bug. It was because of this line:
```c++
const auto& coords = d3plot->get_nodeByID(n)->get_coords()[30];
```

It should have been:
```c++
const auto coords = d3plot->get_nodeByID(n)->get_coords()[30];
```

without a reference.

**Comment by lasso-codie** [comment]
Hmm for sure taking a copy is always safer. Just curious myself why the reference didn't work. Was it the reference of a copy being freed right away? 

Btw LSTC now has an own C/C++ interface for D3plots. They don't release the src but the libs, maybe worth a look at for you. Usability should be lower but performance much higher.
