### ISSUE TITLE
Change of API

### ISSUE THREAD

**Issue by Jdahn** [qd-cae/qd-cae-python#8]
Hi There!

thanks for the further imporvents of the QD-eng package.
I'm having an issue with the new api. (D3plot)
My code:

`Results = D3plot("Base_Model_One_El_Shear_V1.key.d3plot",use_femzip=False,read_states=["disp","stress","strain","history 1 2 3 4 5 6 7 8 9 10 11 12 solid"])
Elem=Results.get_elementByID(Element.solid,1)
Stress=Elem.get_stress()
Time=Results.get_timesteps()
Damage=Elem.get_history()
print('test')`

however the code does not run because of this error.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "//daten/fs1/proj/70_Solid_Model/00_Single_Element_Simulation/Dyna_Extract_Shear.py", line 16, in <module>
    Elem=Results.get_elementByID(Element.solid,1)
NameError: name 'Element' is not defined`

Im calculating with ls dyna version 9.0.1. Do you have any idea how to solve this problem?

Thanks,

J

**Comment by qd-codie** [comment]
hey there,
I'm not entirely sure, whether this is your entire script, but did you import the Element class from the library? 

```python
from qd.cae.dyna import D3plot
from qd.cae.dyna import Element # <-----

d3plot=D3plot("path/to/d3plot")
elem = D3plot.get_elementByIndex(Element.shell, 1)
```

Does this fix it?

**Comment by Jdahn** [comment]
Exactly, I forgot to  import the Element package. 
Thanks!

**Comment by qd-codie** [comment]
glad I could help :)
