### ISSUE TITLE
Binout import failing

### ISSUE THREAD

**Issue by qd-codie** [qd-cae/qd-cae-python#9]
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information. 
```python
from qd.cae.dyna import Binout
```

Traceback (most recent call last): File "<stdin>", line 1, in <module> File "C:\Program Files\Python 3.5\lib\site-packages\qd\cae\dyna.py", line 3, in <module> from .dyna_cpp import * ImportError: DLL load failed: The specified module could not be found.

from **hitendra patil** on youtube.

**Comment by qd-codie** [comment]
Your python version seems fine. The problem sounds quite clear to me. A part of my package is written in C++, thus consists of a dll. Python can not find this dll (real name is  dyna_cpp.pyd) when loading. This means, that the installation is broken somehow. 

I reinstalled it from pip in my python 3.5 myself and did not have any trouble, so I can not reproduce. Did you try reinstallation?

```bash
python -m pip uninstall qd
python -m pip install qd
```

Otherwise go in the folder, and at least check if the following file exists: "C:/Program Files/Python 3.5/lib/site-packages/qd/cae/dyna_cpp.cp35-win_amd64.pyd" and tell me.

**Comment by hrpatil** [comment]
I reinstalled it with the below pip method:
python -m pip uninstall qd
python -m pip install qd
but still, I'm getting the same error.

Below is the tree of qd installed package :

![qd-tree](https://user-images.githubusercontent.com/31008876/29276158-543d70a4-812b-11e7-8977-a6996ff33765.png)


I can find the dyna_cpp.cp35-win_amd64.pyd file.

**Comment by qd-codie** [comment]
Okay you can try several things:

 - Do you use Anaconda python? If no, simply try if it works there (3.5 and 3.6 should work). By the way I compiled it on Anaconda 4.0.0 (64Bit) Python 3.5.3. Your python seems fine, but all distributions sometimes have minor differences, which make them incompatible on windows. They even sometimes lack some dlls.
 - The module dll might not be importable, because it is missing some runtime dlls from windows (there is no error message, but this frequently happens). Do you have the [Microsoft Visual Studio 2015 Redistributional](https://www.microsoft.com/de-at/download/details.aspx?id=48145) installed on your system? If you want to check this before installing the redistributional, import the `.pyd` into [dependency walker](http://www.dependencywalker.com/). I think Anaconda ships almost all of them in itself, but it has been a long time ago, ever since I checked this.

**Comment by hrpatil** [comment]
Hello Mr Codie, 

First of all, I would like to thank you for creating such a nice dyna library. And with Anaconda 4.4.0 and Python version 3.6.1, I can import Binout without any error. 

```
C:\Windows\system32>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qd.cae
>>> from qd.cae.dyna import Binout
>>>
```

Just FYI, I am using Windows 7 ultimate 64 bit with Microsoft Visual Studio 2013 Redistributional.

Thank you very much.
 BR,
Hitendra

**Comment by qd-codie** [comment]
Thank you very much, your comment, that keeps me motivated :) I'm glad, that it is working now. 
I will add your case to the FAQ section later. If you encounter further problems, let me know.

best wishes,
codie
